import { Header } from "@/components/Header";
import { FooterSection } from "@/components/FooterSection";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen">
      <Header />
      <main className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-2 bg-gradient-primary bg-clip-text text-transparent animate-gradient">
            Sonara MVP Privacy Policy
          </h1>
          <p className="text-lg text-muted-foreground mb-8">(Concise)</p>

          <div className="space-y-6">
            <Card className="border-border/50">
              <CardHeader>
                <CardTitle className="text-2xl text-foreground">Purpose and Data</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4 text-foreground">
                <p>
                  This policy covers the Sonara Dynamic Intelligence Platform MVP Prototype, 
                  designed solely for demonstration.
                </p>
                <div className="space-y-2">
                  <p>
                    <strong className="text-primary">Data Collected:</strong> We process CV/Resume 
                    text and Target Job Description text provided by the user.
                  </p>
                  <p>
                    <strong className="text-primary">Mocked Sources:</strong> The prototype uses 
                    simulated data sources (e.g., LinkedIn, Internal Data) only to demonstrate 
                    future capabilities. No real external data is connected or collected.
                  </p>
                  <p>
                    <strong className="text-primary">Usage:</strong> Data is used exclusively for 
                    generating the Skill Profile, running Gap Analysis, and providing Personalized 
                    Recommendations.
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card className="border-border/50">
              <CardHeader>
                <CardTitle className="text-2xl text-foreground">
                  Data Security and Storage (CRITICAL PROTOTYPE NOTE)
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4 text-foreground">
                <p className="font-semibold">
                  To ensure maximum transparency and security for this demonstration:
                </p>
                <div className="space-y-3 pl-4 border-l-2 border-primary">
                  <p>
                    <strong className="text-primary">In-Memory Only:</strong> All data provided 
                    and generated by Sonara is processed exclusively in-memory within your current 
                    browser session.
                  </p>
                  <p>
                    <strong className="text-primary">No Persistence:</strong> No data is stored, 
                    saved, or persisted on any server, database, or external storage.
                  </p>
                  <p>
                    <strong className="text-primary">Data Deletion:</strong> All information is 
                    automatically deleted when your browser session concludes.
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card className="border-border/50">
              <CardHeader>
                <CardTitle className="text-2xl text-foreground">Future Compliance</CardTitle>
              </CardHeader>
              <CardContent className="text-foreground">
                <p>
                  In a live enterprise deployment, data handling will be governed by a comprehensive 
                  policy. The user's "Sharing Status" toggle will control access for L&D teams, 
                  ensuring data is only shared with explicit user permission.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
      <FooterSection />
    </div>
  );
};

export default PrivacyPolicy;
