import { Header } from "@/components/Header";
import { FooterSection } from "@/components/FooterSection";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      <main className="flex-1 container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto space-y-6">
          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold bg-gradient-primary bg-clip-text text-transparent animate-gradient mb-2">Terms of Service</h1>
            <p className="text-muted-foreground">Effective Date: November 9, 2025</p>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>1. Acceptance of Terms</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground/80">
                By accessing or using the Sonara Dynamic Intelligence Platform MVP Prototype ("Sonara," "the Service"), 
                you agree to be bound by these Terms of Service ("Terms"). This Service is a non-production, proof-of-concept 
                application designed solely for demonstration purposes, primarily for the SAP competition. DO NOT rely on the 
                Service for professional, career, or critical business decisions.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>2. Service Description (Prototype Status)</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground/80 mb-4">
                Sonara is a simulated intelligence platform that extracts, synthesizes, and visualizes professional skill data 
                from user-provided text (like CVs and job descriptions) to perform gap analysis and offer personalized, mock 
                learning recommendations.
              </p>
              <p className="text-foreground/80 font-semibold">
                Prototype Limitation: The Service is provided AS-IS and is subject to frequent changes, outages, and potential 
                inaccuracies (hallucinations). We do not guarantee the Service's availability, accuracy, or suitability for any purpose.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>3. Privacy and Data Handling</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground/80 mb-4">
                Your use of the Service is also governed by the Sonara MVP Privacy Policy. By accepting these Terms, you 
                acknowledge and agree to the Privacy Policy, specifically the following critical points:
              </p>
              <ul className="list-disc list-inside space-y-2 text-foreground/80">
                <li><strong>In-Memory Processing:</strong> All user input data is processed in-memory only.</li>
                <li><strong>No Persistence:</strong> No user data is stored, saved, or persisted on any backend database or server after the browser session ends.</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>4. User Obligations</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground/80 mb-4">
                You agree to use the Service only for its intended purpose—a technology demonstration—and in compliance with 
                all applicable laws. You agree not to:
              </p>
              <ul className="list-disc list-inside space-y-2 text-foreground/80">
                <li>Attempt to reverse engineer, decompile, or hack the Service.</li>
                <li>Input any sensitive, confidential, or proprietary information that you do not have the right to share.</li>
                <li>Use the output for any official internal or external reporting or decision-making.</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>5. Intellectual Property and Output Ownership</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="list-disc list-inside space-y-2 text-foreground/80">
                <li><strong>Service IP:</strong> All intellectual property rights in the Sonara platform (code, design, visualization methodologies) belong to the Service creators.</li>
                <li><strong>Output Ownership:</strong> You retain all ownership rights to the raw data you input (CV text, job descriptions). The resulting skill profiles, analysis reports, and recommendations generated by the Service are owned by the user providing the input data.</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>6. DISCLAIMER OF WARRANTIES (IMPORTANT)</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground/80 font-semibold">
                THE SONARA MVP PROTOTYPE IS PROVIDED "AS IS," WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT 
                NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT. THE 
                CREATORS OF THE SERVICE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF INACCURACIES.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>7. Limitation of Liability</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-foreground/80 font-semibold">
                IN NO EVENT SHALL THE CREATORS OF THE SONARA MVP PROTOTYPE BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, 
                WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION WITH THE SERVICE OR 
                THE USE OR OTHER DEALINGS IN THE SERVICE.
              </p>
            </CardContent>
          </Card>
        </div>
      </main>
      <FooterSection />
    </div>
  );
};

export default TermsOfService;
